# Generated by Django 4.0.4 on 2022-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(null=True, upload_to='photos/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(null=True, upload_to='photos/product'),
        ),
    ]
