# Generated by Django 4.0.4 on 2022-06-29 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='photos/product', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(null=True, upload_to='photos/product', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='images3',
            field=models.ImageField(null=True, upload_to='photos/product', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
    ]
