# Generated by Django 4.0.4 on 2022-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitemm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemm',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=10, null=True),
        ),
    ]
