# Generated by Django 4.0.4 on 2022-06-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitemm_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_offer_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
