# Generated by Django 4.0.4 on 2022-06-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
