# Generated by Django 4.0.4 on 2022-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referel_activated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='referel_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
