# Generated by Django 4.0.4 on 2022-05-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('descriptions', models.TextField(max_length=250, unique=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/category')),
            ],
        ),
    ]
