# Generated by Django 4.0.4 on 2022-06-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
    ]
