# Generated by Django 4.0.4 on 2022-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_razorpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Corfirmed', 'Corfirmed'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Canelled', 'Cancelled'), ('Returned', 'Returned')], default='Confirmed', max_length=20),
        ),
    ]
